#!/usr/bin/python3
import sys

def factorize(number):
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return i, number // i
    return number, 1

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

input_file = sys.argv[1]

try:
    with open(input_file, 'r') as file:
        for line in file:
            number = int(line)
            factors = factorize(number)
            print(f"{number}={factors[0]}*{factors[1}")

except FileNotFoundError:
    print(f"File '{input_file}' not found.")
except ValueError:
    print("Invalid input in the file. Make sure all lines are valid natural numbers greater than 1.")

